### ISSUE TITLE
"Application has stopped" error while initializing MapboxNavigation

### ISSUE THREAD

**Issue by BoogieMAN2K** [NAXAM/mapboxnavigationui-android-binding#1]
I'm initializing the MapboxNavigation class during the OnCreate method and after the line gets executed android is returning me this message. The thing is, the navigation is getting created correctly and everything works fine after that but the Application output doesn't return any message or trace related and I don't know how to fix this issue.

Any help would be greatly appreciated...

**Comment by BoogieMAN2K** [comment]
To add more information about the crash, I'm using MvvmCross and using LogCat the device return this:

`Error (21218) / AndroidRuntime: FATAL EXCEPTION: main
Error (21218) / AndroidRuntime: Process: com.Tackzee_Rider:lost, PID: 21218
Error (21218) / AndroidRuntime: java.lang.UnsatisfiedLinkError: No implementation found for void md50ba1a21c88855965b540681eb0c3b913.MainApplication.n_onCreate() (tried Java_md50ba1a21c88855965b540681eb0c3b913_MainApplication_n_1onCreate and Java_md50ba1a21c88855965b540681eb0c3b913_MainApplication_n_1onCreate__)
Error (21218) / AndroidRuntime: 	at md50ba1a21c88855965b540681eb0c3b913.MainApplication.n_onCreate(Native Method)
Error (21218) / AndroidRuntime: 	at md50ba1a21c88855965b540681eb0c3b913.MainApplication.onCreate(MainApplication.java:34)
Error (21218) / AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1118)
Error (21218) / AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5817)
Error (21218) / AndroidRuntime: 	at android.app.ActivityThread.-wrap1(Unknown Source:0)
Error (21218) / AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1677)
Error (21218) / AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
Error (21218) / AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
Error (21218) / AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6567)
Error (21218) / AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
Error (21218) / AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
Error (21218) / AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
`

**Comment by tuyen-vuduc** [comment]
@BoogieMAN2K

Error message is very clear
```
No implementation found for void md50ba1a21c88855965b540681eb0c3b913.MainApplication.n_onCreate()
```
Plz make sure your application class is written correctly.

MvvmCross won't impact this binding library.

Cheers.

**Comment by tuyen-vuduc** [comment]
@BoogieMAN2K Haven't heard back from you. Is that ok now?

**Comment by MAX-POLKOVNIK** [comment]
@tuyen-vuduc Hello again!

I got same java.lang.UnsatisfiedLinkError exception when I call LostLocationEngine.Activate() or others LostLocationEngine methods.

There is my sample:
[TestMapbox2Naxam.zip](https://github.com/NAXAM/mapboxnavigationui-android-binding/files/1761360/TestMapbox2Naxam.zip)

Application class is written correctly and works when app starts.

I guess Android throws exception due to Mapzen starts service in another process. Generated AndroidManifest contains this line:
```
<service android:name="com.mapzen.android.lost.internal.FusedLocationProviderService" android:process=":lost" />
```

So, I google this problem and found this [https://bugzilla.xamarin.com/show_bug.cgi?id=51940](url).

Any ideas how to fix this?

**Comment by Sectar** [comment]
+1, have same problem. Any progress?

**Comment by JPSiller** [comment]
Hi, 

I hope this can help, in my case the error happens because I have a custom class for MainApplication which inherits from Application, Application.IActivityLifecycleCallbacks. On this class I have an override for OnCreate (which still calls base.OnCreate). 

If I remove this override I stop getting the error. It seems that the MapzenLost process gets confused by having this OnCreate override. I'm also using GoogleLocationEngine instead of LostLocationEngine. I've never been able to make LostLocationEngine work with LocationLayerPlugin.

**Comment by tipa** [comment]
@JPSiller Experiencing the same issue (with another library binding). Have you ever found a solution/workaround to this problem?

**Comment by andremorata** [comment]
I was experiencing the exact same problem which weirdly started apparently from nothing. So, after almost 4 hours looking into this, I have decided to move the code from OnCreate() method to the ctor() based on @JPSiller comment and now the problem is gone. I still need to test a little bit more, but at least the app is able to start correctly now.
